apiVersion: v1
kind: Service
metadata:
  name: sensormgmt-service
  namespace: scada
spec:
  selector:
    app: sensormgmt-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-sensormgmt
  namespace: scada
spec:
  selector:
    app: postgres-sensormgmt
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sensormgmt
  namespace: scada
spec:
  selector:
    app: redis-sensormgmt
  ports:
    - port: 6379
      targetPort: 6379
