// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SensorManagementService.Data;

#nullable disable

namespace SensorManagementService.Migrations
{
    [DbContext(typeof(SensorMgmtDbContext))]
    [Migration("20260615211416_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SensorManagementService.Models.Sensor", b =>
                {
                    b.Property<string>("SensorId")
                        .HasColumnType("text")
                        .HasColumnName("sensor_id");

                    b.Property<string>("AlarmThresholds")
                        .HasColumnType("jsonb")
                        .HasColumnName("alarm_thresholds");

                    b.Property<DateTimeOffset?>("BlockedUntilAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_until_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quality");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double?>("ValueMax")
                        .HasColumnType("double precision")
                        .HasColumnName("value_max");

                    b.Property<double?>("ValueMin")
                        .HasColumnType("double precision")
                        .HasColumnName("value_min");

                    b.HasKey("SensorId");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("SensorManagementService.Models.SensorStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_status");

                    b.Property<string>("OldStatus")
                        .HasColumnType("text")
                        .HasColumnName("old_status");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sensor_id");

                    b.HasKey("Id");

                    b.ToTable("sensor_status_history", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
