apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: scada
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
