apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: scada
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: auth-service
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: scada
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: scada
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ingestion-service
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consensus-service
  namespace: scada
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: consensus-service
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensormgmt-service
  namespace: scada
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: sensormgmt-service
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: scada
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: notification-service
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: scada
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: analytics-service
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: scada
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
