apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - kafka/deployment.yaml
  - kafka/service.yaml
  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - ingestion-service/deployment.yaml
  - ingestion-service/service.yaml
  - consensus-service/deployment.yaml
  - consensus-service/service.yaml
  - sensormgmt-service/deployment.yaml
  - sensormgmt-service/service.yaml
  - notification-service/deployment.yaml
  - notification-service/service.yaml
  - analytics-service/deployment.yaml
  - analytics-service/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
