apiVersion: v1
kind: Secret
metadata:
  name: scada-secrets
  namespace: scada
type: Opaque
stringData:
  jwt-key: "scada-jwt-dev-secret-key-must-be-at-least-32-bytes-long!"
  postgres-password: "postgres"
  influx-token: "scada-influx-token"
  aes-key: "Yl+vBqkPaMnqOoyFWsrSMze/2W1srfEXvXPSD7SrSJk="
  ecdsa-private-key: "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgJn8OTamdhmY1rCz730gotfNAGR2dT80DV3M+sKUzfEyhRANCAASuko3bEGVdf45IA/49UT0F1K5jnQdRM/Mp8m3QN+8L4nUF61MHk02Y/mvJgLuJTZVdSzqmHEQz/WWRkO2OgFAX"
  ecdsa-public-key: "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAErpKN2xBlXX+OSAP+PVE9BdSuY50HUTPzKfJt0DfvC+J1BetTB5NNmP5ryYC7iU2VXUs6phxEM/1lkZDtjoBQFw=="
