// <auto-generated />
using System;
using ConsensusService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsensusService.Migrations
{
    [DbContext(typeof(ConsensusDbContext))]
    [Migration("20260615214622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsensusService.Models.ConsensusResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("ConsensusValue")
                        .HasColumnType("double precision")
                        .HasColumnName("consensus_value");

                    b.Property<int>("ContributingSensors")
                        .HasColumnType("integer")
                        .HasColumnName("contributing_sensors");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.ToTable("consensus_results", (string)null);
                });

            modelBuilder.Entity("ConsensusService.Models.QualityChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<double>("ConsensusValue")
                        .HasColumnType("double precision")
                        .HasColumnName("consensus_value");

                    b.Property<double>("DeviationSigma")
                        .HasColumnType("double precision")
                        .HasColumnName("deviation_sigma");

                    b.Property<string>("NewQuality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_quality");

                    b.Property<string>("PreviousQuality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("previous_quality");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sensor_id");

                    b.Property<double>("SensorValue")
                        .HasColumnType("double precision")
                        .HasColumnName("sensor_value");

                    b.HasKey("Id");

                    b.ToTable("quality_changes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
